### ISSUE TITLE
reimplement move prop

### ISSUE THREAD

**Issue by TornadoKirby** [anish2690/vue-draggable-next#1]
hello! 
on the original vue.draggable library, there is a [move property](https://github.com/SortableJS/Vue.Draggable#move) that allows a drag to be cancelled if the provided function returns false. it is [implemented here](https://github.com/SortableJS/Vue.Draggable/blob/2fd91d6af51febf3b5dde9e5bac93afb9231b045/src/vuedraggable.js#L457) in the original component. 
this would be very helpful to have access to in this version. however, i realize that the original code used some functionality from vue 2 that isn't present anymore in vue-next, so you've [left it stubbed](https://github.com/anish2690/vue-draggable-next/blob/c1be68e6ed75bab7649fe2bf41598d9f3f00095b/src/VueDraggableNext.ts#L327) in your code. would it be possible for you to make it at least run the function passed in the prop like it was before (like `return onMove(evt, originalEvent);`)? 
thanks for your time!

**Comment by anish2690** [comment]
hey, @TornadoKirby  added support for move property https://github.com/anish2690/vue-draggable-next/releases/tag/1.0.3
