### ISSUE TITLE
updateOptions can be triggered before _sortable is initialized

### ISSUE THREAD

**Issue by puyt** [anish2690/vue-draggable-next#11]
Sorry for not providing any code example since I can't always reproduce it.

It's completely fixed for me when using `$nextTick` inside `updateOptions`.

![image](https://user-images.githubusercontent.com/3668615/119692501-c0b76080-be4b-11eb-9279-d50628648667.png)

![image](https://user-images.githubusercontent.com/3668615/119692384-a8474600-be4b-11eb-878a-1a323daa8512.png)

**Comment by anish2690** [comment]
@puyt thanks for reporting that, code example will be helpful to resolve this once you are ready you can reopen the issue.
