### ISSUE TITLE
evt.draggedContext.futureIndex not updated when dragging item from one section to another

### ISSUE THREAD

**Issue by mfjonker** [anish2690/vue-draggable-next#12]
Description:
I want to track the futureIndex of the dragged item within the onMove event in order to potentially return false (i.e. to cancel). 

What happens:
As long as the dragged item remains within the section in which the drag originated, the evt.draggedContext.futureIndex returns the correct futureIndex. However, as soon as the item is dragged into another section, the futureIndex stays zero. 

What I expected:
I expected evt.draggedContext.futureIndex to report the correct index (also after dragging an item into another section). See the attached .gif for an example screenshot.

![output](https://user-images.githubusercontent.com/4223141/122657128-015f7c80-d161-11eb-8121-0cf0163a3a99.gif)
.

**Comment by anish2690** [comment]
@mfjonker please share  the code sample so I can take a look

**Comment by mfjonker** [comment]
@anish2690 Sure, I can send you an invitation to the project - but perhaps a simple example is sufficient? 
See https://github.com/mfjonker/anish-draggable-test , which is a slight modification of the basic demo example.

**Comment by mfjonker** [comment]
@anish2690 Do you perhaps have an update of this issue? Thank you!

**Comment by anish2690** [comment]
@mfjonker you have to listen for `change` event , once you moved out from one instance to another there will be a `added` event for destination and `removed` for source events.

**Comment by mfjonker** [comment]
@anish2690 Thank you for your suggestion. Two quick questions: a) Does the change event also allow you to cancel the drag? That is why I needed the evt.draggedContext.futureIndex to return the correct futureIndex; if you return "false" the drag is canceled. b) Wouldn't it be preferable to have the evt.draggedContext.futureIndex to return the corect value?

**Comment by mfjonker** [comment]
@anish2690 I checked the SortableJS /
vue.draggable.next project and evt.draggedContext.futureIndex is not always zero when dragging an item from one section to another in their implementation; hence it does appear to be an error in the vue-draggable-next implementation. It would be truly great if you could fix this?

**Comment by anish2690** [comment]
Sure I'll check that out

**Comment by mfjonker** [comment]
Hi @anish2690, apologies for spamming (!) and a quick question to see if there is any progress on this issue. Many thanks!

**Comment by anish2690** [comment]
@mfjonker i'm not able find any errors it will show future index as 0 because that element is not added to the second instance of drag space.

**Comment by mfjonker** [comment]
Hi @anish2690, as promised the link to the test-example based on the vue.draggable.next library:
https://github.com/mfjonker/vue.draggable.next-test
(The animated gifs are in the repository as well.)

**Comment by anish2690** [comment]
https://github.com/anish2690/vue-draggable-next/releases/tag/2.1.0
