### ISSUE TITLE
On the problem of dragging elements across levels in tree recursive components

### ISSUE THREAD

**Issue by lybyq** [anish2690/vue-draggable-next#13]
原来的move方法中是可以返回relatedContext参数的，其中能解构出 index，element，list，component，但是我在递归组件中跨层级移动元素relatedContext中只能解构出list，componet两个参数而且list值也不对，请您帮助我下，谢谢

The original move method can return relatedcontext parameters, in which ‘index’, ‘element’, ‘list’ and ‘component’ can be deconstructed, but I can only deconstruct ‘list’ and ‘component’ parameters in relatedcontext when I move elements across levels in recursive components, and the list value is also wrong. Please help me. Thank you

**Comment by anish2690** [comment]
@lybyq please share a sample repo where i can see the issue.

**Comment by lybyq** [comment]
Hello, this is the tree recursive component I wrote
`<draggable
        v-show="isOpen"
        v-if="isFolder"
        v-model="tree.children"
        tag="ul"
        class="wrapper"
        :class="{'space': tree.level === 2, 'space2': tree.level === 3}"
        v-bind="options"
        :move="onMove"
        @start="onStart"
        @end="onEnd"
        @change="updateDrag"
        @unchoose="unchoose"
      >
        <transition-group>
          <StudyTree
            v-for="(item, idx) in tree.children"
            :key="item.id || idx + '_s'"
            :tree="item"
            :index="idx"
            :courseId="courseId"
            v-bind="$attrs"
          />
        </transition-group>
      </draggable>`

![1627398495(1)](https://user-images.githubusercontent.com/29450465/127180175-2d176b61-586b-4ab9-9504-86b0d98c7313.png)



If I drag each other at the same level of the tree, the move method returns the correct parameters
![1627398546(1)](https://user-images.githubusercontent.com/29450465/127179899-4d164d83-6d4f-4bc1-9eda-0c5a66f261ab.png)

But if I drag across levels, the move method returns only two parameters
![1627398579(1)](https://user-images.githubusercontent.com/29450465/127180013-bf4a5641-b187-4e6b-9a21-6acf49e1a2bf.png)

**Comment by lybyq** [comment]
Please help or provide solutions. Thank you Anish

拜托您给与下帮助，或者提供下解决思路，谢谢您

**Comment by anish2690** [comment]
@lybyq please provide a reproduction repo and re-open the ticket
