### ISSUE TITLE
How can I change the cursor icon when dragging an item?

### ISSUE THREAD

**Issue by cuoppro9x** [anish2690/vue-draggable-next#18]
Hello, that's a great plugin !
I only have a question: How can I change the cursor icon when dragging an item?
Many thanks !!

**Comment by anish2690** [comment]
@cuoppro9x use `  dragClass="drag-preview"` and style them.
![image](https://user-images.githubusercontent.com/22445409/148682773-b2100c3e-e8bb-4b4c-9b5f-7a4b884a10b0.png)
