### ISSUE TITLE
Is there anyway to make one element not draggable?

### ISSUE THREAD

**Issue by LovelyAndy** [anish2690/vue-draggable-next#20]
Just a way to make something completely unmovable? I see there is the `disabled` option, but I cannot figure out how to make it work for a single element.

Cheers on the great library!

**Comment by anish2690** [comment]
@LovelyAndy filter should work here. PFA
![image](https://user-images.githubusercontent.com/22445409/148682390-5f2ae18d-f54b-4d57-a6b8-fdaa277a6e20.png)

**Comment by LovelyAndy** [comment]
Thanks for the comment and help! Cheers!
