### ISSUE TITLE
vue-router dependency only used for demo

### ISSUE THREAD

**Issue by Celant** [anish2690/vue-draggable-next#21]
Hey,

After installing this package I can see that I now have `vue-router` installed. From what I can see, the router is only actually used in the demo application and is not actually a dependency of vue-draggable-next itself. Is there any reason for this, or can I submit a PR to move this into the dev dependencies?

**Comment by anish2690** [comment]
This should be fixed now (https://github.com/anish2690/vue-draggable-next/pull/22)
