### ISSUE TITLE
BUG:The first drag will, in any case, cause the dragged element to be placed in the first place.

### ISSUE THREAD

**Issue by 1014670860** [anish2690/vue-draggable-next#28]
The first drag will, in any case, cause the dragged element to be placed in the first place.The currently dragged element contains canvas

**Comment by anish2690** [comment]
@1014670860 Please provide a repo which showcasing problem.

**Comment by donaldzou** [comment]
I believe this encountered when draggable doesn't know how many item in your list. I found a solution and will make a PR
