### ISSUE TITLE
when use it in typescript ,it cannot be recognized correctly

### ISSUE THREAD

**Issue by bigmeow** [anish2690/vue-draggable-next#3]
![image](https://user-images.githubusercontent.com/10484248/92463272-2d2afa80-f1fe-11ea-81a4-b165978537af.png)

My temporary solution is:
```ts
// shims-vue.d.ts
declare module "*.vue" {
    import { defineComponent } from "vue";
    const component: ReturnType<typeof defineComponent>;
    export default component;
}
// add
declare module "vue-draggable-next" {
    export { VueDraggableNext } from "vue-draggable-next/dist/src/index";
}
```

**Comment by joel785454405** [comment]
Just write like this👇

declare module 'vue-draggable-next';

**Comment by joel785454405** [comment]
> ![image](https://user-images.githubusercontent.com/10484248/92463272-2d2afa80-f1fe-11ea-81a4-b165978537af.png)
> 
> My temporary solution is:
> 
> ```ts
> // shims-vue.d.ts
> declare module "*.vue" {
>     import { defineComponent } from "vue";
>     const component: ReturnType<typeof defineComponent>;
>     export default component;
> }
> // add
> declare module "vue-draggable-next" {
>     export { VueDraggableNext } from "vue-draggable-next/dist/src/index";
> }
> ```
reply 👀

**Comment by anish2690** [comment]
@bigmeow is something I have it on my plan for timing just  use `declare module 'vue-draggable-next'`

**Comment by MaybeQHL** [comment]
@anish2690 I think it should be specified in the types field of package.json to avoid error reporting.

**Comment by bigmeow** [comment]
I hope it to be recognized automatically

**Comment by anish2690** [comment]
https://github.com/anish2690/vue-draggable-next/pull/4 added support for type definition
