### ISSUE TITLE
[Vue warn]: (deprecation WATCH_ARRAY) "watch"

### ISSUE THREAD

**Issue by porkus1990** [anish2690/vue-draggable-next#30]
The Vue warn `[Vue warn]: (deprecation WATCH_ARRAY) "watch" option or vm.$watch on an array value will no longer trigger on array mutation unless the "deep" option is specified.` occurs.

I think the deep: true option is missing for realList.

**Comment by 527604382** [comment]
i think so.watch realList need to add deep property

**Comment by anish2690** [comment]
@porkus1990 looks like deep watch might required in that case or just depends on @change="onChangeList" event
