### ISSUE TITLE
Ts error when assiging class to `draggable` attribute

### ISSUE THREAD

**Issue by LovelyAndy** [anish2690/vue-draggable-next#31]
Hello, I am getting a ts error on the `draggable` attribute (error shown below) and wondering what I can do here. I saw the `draggable` attribute on the [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) library, but perhaps you just don't need it in your version?
The elements are all still draggable so maybe I can go without it?

Any input would be greatly appreciated!

```
Type '".machine"' is not assignable to type 'Booleanish | undefined'.
draggable=".machine"
```

ts error:
![image](https://user-images.githubusercontent.com/68723584/162289857-94220e85-68fb-420a-8fa1-6369fa5f9c9f.png)

Section from the Vue.Draggable library using the `draggable` attribute:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/68723584/162289407-f18ba448-db46-4e53-b79c-7e7cb87c0f8f.png">

**Comment by anish2690** [comment]
@LovelyAndy draggable prop is not required,  by default it is on list.
