### ISSUE TITLE
How to allow dragging between different lists?

### ISSUE THREAD

**Issue by LeaVerou** [anish2690/vue-draggable-next#38]
Hello, thanks for making this plugin!

I'm currently using it for drag & drop to reorder items in two lists, but I also want to allow d&d *between* the two lists. Is that possible? If so, how?

Thanks!

**Comment by anish2690** [comment]
@LeaVerou yes it possible refer example and make few modification that should work https://vue-draggable-next.vercel.app/#/clone

<img width="801" alt="image" src="https://user-images.githubusercontent.com/22445409/185533312-0b3add1d-9032-4075-95ef-8dd6f9df2326.png">
