### ISSUE TITLE
Typescript definition files missing

### ISSUE THREAD

**Issue by lukasvan3l** [anish2690/vue-draggable-next#53]
The `package.json` within `node_modules` refers to a `d.ts` typescript definition file

![image](https://github.com/anish2690/vue-draggable-next/assets/169870/e7c2bcbf-578a-4e81-9d81-96e5deed6bdf)

In my `node_modules` folder I don't see this file

![image](https://github.com/anish2690/vue-draggable-next/assets/169870/829fd261-594b-4c99-8979-c54849596d5f)

**Comment by taidaid** [comment]
This happened in the change to version 2.2.0. Version 2.1.0 seems fine, reverting to it solved my type problem.

**Comment by anish2690** [comment]
this issue should be fixed in v2.2.1 (https://github.com/anish2690/vue-draggable-next/releases)
