### ISSUE TITLE
interface OpenObject is private

### ISSUE THREAD

**Issue by cinyearchan** [anish2690/vue-draggable-next#63]
when I use ts-morph to emit file, console shows "Default export of the module has or is using private name 'OpenObject'", interface OpenObject is private, maybe should export

**Comment by maslunde** [comment]
Hi, why did this get closed as not planned? It's a real issue and I have to downgrade because of it. 
![image](https://github.com/user-attachments/assets/f9ec3441-86ef-4c43-b469-724613b37151)
